// Fabric.js 캔버스용 상세페이지 템플릿
// 템플릿은 loadFromJSON으로 바로 불러올 수 있는 형식

export interface CanvasTemplate {
  id: string;
  name: string;
  category: 'fruit' | 'vegetable' | 'seafood' | 'general';
  description: string;
  thumbnail: string; // 색상 코드 또는 이미지
  canvasHeight: number;
  fabricJson: object;
}

// 과일 상세페이지 템플릿 (타이벡 감귤 스타일)
const fruitDetailTemplate: CanvasTemplate = {
  id: 'fruit-citrus',
  name: '과일 상세페이지 (감귤 스타일)',
  category: 'fruit',
  description: '제주 감귤 스타일의 프리미엄 과일 상세페이지',
  thumbnail: '#FF9800',
  canvasHeight: 3500,
  fabricJson: {
    version: '6.0.0',
    objects: [
      // 섹션 1: 헤더 배너
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: 860,
        height: 400,
        fill: '#FFF8E1',
        selectable: true,
        _customId: 'header-bg',
        _customName: '헤더 배경',
      },
      {
        type: 'textbox',
        left: 430,
        top: 80,
        width: 700,
        text: '🍊 제주 특산품',
        fontSize: 24,
        fontFamily: 'Noto Sans KR',
        fontWeight: 'normal',
        fill: '#FF9800',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
        _customId: 'header-badge',
        _customName: '상단 라벨',
      },
      {
        type: 'textbox',
        left: 430,
        top: 140,
        width: 700,
        text: '햇살 가득 머금은\n제주 노지 감귤',
        fontSize: 48,
        fontFamily: 'Noto Sans KR',
        fontWeight: 'bold',
        fill: '#E65100',
        textAlign: 'center',
        originX: 'center',
        lineHeight: 1.3,
        selectable: true,
        _customId: 'main-title',
        _customName: '메인 타이틀',
      },
      {
        type: 'textbox',
        left: 430,
        top: 280,
        width: 600,
        text: '달콤함과 새콤함의 완벽한 조화\n자연 그대로의 신선함을 담았습니다',
        fontSize: 18,
        fontFamily: 'Noto Sans KR',
        fontWeight: 'normal',
        fill: '#666666',
        textAlign: 'center',
        originX: 'center',
        lineHeight: 1.5,
        selectable: true,
        _customId: 'sub-title',
        _customName: '서브 타이틀',
      },

      // 섹션 2: 상품 소개
      {
        type: 'rect',
        left: 0,
        top: 420,
        width: 860,
        height: 600,
        fill: '#FFFFFF',
        selectable: true,
        _customId: 'intro-bg',
        _customName: '상품소개 배경',
      },
      {
        type: 'textbox',
        left: 430,
        top: 460,
        width: 600,
        text: '대체 무슨 감귤이길래?',
        fontSize: 18,
        fontFamily: 'Noto Sans KR',
        fontWeight: 'normal',
        fill: '#999999',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
        _customId: 'intro-question',
        _customName: '인트로 질문',
      },
      {
        type: 'textbox',
        left: 430,
        top: 500,
        width: 700,
        text: '저희가 판매하는 감귤은요~!',
        fontSize: 28,
        fontFamily: 'Noto Sans KR',
        fontWeight: 'bold',
        fill: '#333333',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
        _customId: 'intro-title',
        _customName: '소개 제목',
      },
      // 특징 포인트들
      {
        type: 'rect',
        left: 80,
        top: 570,
        width: 700,
        height: 60,
        fill: '#FFF3E0',
        rx: 12,
        ry: 12,
        selectable: true,
        _customId: 'feature-1-bg',
        _customName: '특징1 배경',
      },
      {
        type: 'textbox',
        left: 100,
        top: 585,
        width: 660,
        text: '✓ 제주 햇살을 가득 받은 노지 재배 감귤',
        fontSize: 18,
        fontFamily: 'Noto Sans KR',
        fontWeight: '500',
        fill: '#333333',
        selectable: true,
        _customId: 'feature-1-text',
        _customName: '특징1 텍스트',
      },
      {
        type: 'rect',
        left: 80,
        top: 650,
        width: 700,
        height: 60,
        fill: '#FFF3E0',
        rx: 12,
        ry: 12,
        selectable: true,
        _customId: 'feature-2-bg',
        _customName: '특징2 배경',
      },
      {
        type: 'textbox',
        left: 100,
        top: 665,
        width: 660,
        text: '✓ 당도 선별로 엄선된 프리미엄 품질',
        fontSize: 18,
        fontFamily: 'Noto Sans KR',
        fontWeight: '500',
        fill: '#333333',
        selectable: true,
        _customId: 'feature-2-text',
        _customName: '특징2 텍스트',
      },
      {
        type: 'rect',
        left: 80,
        top: 730,
        width: 700,
        height: 60,
        fill: '#FFF3E0',
        rx: 12,
        ry: 12,
        selectable: true,
        _customId: 'feature-3-bg',
        _customName: '특징3 배경',
      },
      {
        type: 'textbox',
        left: 100,
        top: 745,
        width: 660,
        text: '✓ 산지 직송으로 신선하게 배송',
        fontSize: 18,
        fontFamily: 'Noto Sans KR',
        fontWeight: '500',
        fill: '#333333',
        selectable: true,
        _customId: 'feature-3-text',
        _customName: '특징3 텍스트',
      },
      // 이미지 영역 플레이스홀더
      {
        type: 'rect',
        left: 180,
        top: 830,
        width: 500,
        height: 160,
        fill: '#F5F5F5',
        rx: 16,
        ry: 16,
        stroke: '#E0E0E0',
        strokeWidth: 2,
        strokeDashArray: [8, 4],
        selectable: true,
        _customId: 'product-image-placeholder',
        _customName: '상품 이미지 영역',
      },
      {
        type: 'textbox',
        left: 430,
        top: 890,
        width: 400,
        text: '📷 상품 이미지를\n여기에 드래그하세요',
        fontSize: 16,
        fontFamily: 'Noto Sans KR',
        fontWeight: 'normal',
        fill: '#999999',
        textAlign: 'center',
        originX: 'center',
        lineHeight: 1.4,
        selectable: true,
        _customId: 'image-placeholder-text',
        _customName: '이미지 안내 텍스트',
      },

      // 섹션 3: 특징 아이콘
      {
        type: 'rect',
        left: 0,
        top: 1040,
        width: 860,
        height: 350,
        fill: '#FFF8E1',
        selectable: true,
        _customId: 'features-bg',
        _customName: '특징 섹션 배경',
      },
      {
        type: 'textbox',
        left: 430,
        top: 1080,
        width: 700,
        text: '맛있을 수 밖에 없는 프리미엄 감귤',
        fontSize: 24,
        fontFamily: 'Noto Sans KR',
        fontWeight: 'bold',
        fill: '#333333',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
        _customId: 'features-title',
        _customName: '특징 섹션 제목',
      },
      // 특징 아이콘 박스들
      {
        type: 'rect',
        left: 60,
        top: 1150,
        width: 160,
        height: 180,
        fill: '#FFFFFF',
        rx: 16,
        ry: 16,
        selectable: true,
        _customId: 'icon-box-1',
        _customName: '아이콘 박스 1',
      },
      {
        type: 'textbox',
        left: 140,
        top: 1180,
        width: 100,
        text: '🍊',
        fontSize: 48,
        textAlign: 'center',
        originX: 'center',
        selectable: true,
        _customId: 'icon-1',
        _customName: '아이콘 1',
      },
      {
        type: 'textbox',
        left: 140,
        top: 1250,
        width: 140,
        text: '당도 보장',
        fontSize: 16,
        fontFamily: 'Noto Sans KR',
        fontWeight: 'bold',
        fill: '#333333',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
        _customId: 'icon-title-1',
        _customName: '아이콘 제목 1',
      },
      {
        type: 'textbox',
        left: 140,
        top: 1280,
        width: 140,
        text: '10brix 이상',
        fontSize: 13,
        fontFamily: 'Noto Sans KR',
        fill: '#888888',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
        _customId: 'icon-desc-1',
        _customName: '아이콘 설명 1',
      },
      // 아이콘 박스 2
      {
        type: 'rect',
        left: 240,
        top: 1150,
        width: 160,
        height: 180,
        fill: '#FFFFFF',
        rx: 16,
        ry: 16,
        selectable: true,
        _customId: 'icon-box-2',
        _customName: '아이콘 박스 2',
      },
      {
        type: 'textbox',
        left: 320,
        top: 1180,
        width: 100,
        text: '🚚',
        fontSize: 48,
        textAlign: 'center',
        originX: 'center',
        selectable: true,
        _customId: 'icon-2',
        _customName: '아이콘 2',
      },
      {
        type: 'textbox',
        left: 320,
        top: 1250,
        width: 140,
        text: '산지직송',
        fontSize: 16,
        fontFamily: 'Noto Sans KR',
        fontWeight: 'bold',
        fill: '#333333',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
        _customId: 'icon-title-2',
        _customName: '아이콘 제목 2',
      },
      {
        type: 'textbox',
        left: 320,
        top: 1280,
        width: 140,
        text: '수확 후 바로 배송',
        fontSize: 13,
        fontFamily: 'Noto Sans KR',
        fill: '#888888',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
        _customId: 'icon-desc-2',
        _customName: '아이콘 설명 2',
      },
      // 아이콘 박스 3
      {
        type: 'rect',
        left: 420,
        top: 1150,
        width: 160,
        height: 180,
        fill: '#FFFFFF',
        rx: 16,
        ry: 16,
        selectable: true,
        _customId: 'icon-box-3',
        _customName: '아이콘 박스 3',
      },
      {
        type: 'textbox',
        left: 500,
        top: 1180,
        width: 100,
        text: '🏝️',
        fontSize: 48,
        textAlign: 'center',
        originX: 'center',
        selectable: true,
        _customId: 'icon-3',
        _customName: '아이콘 3',
      },
      {
        type: 'textbox',
        left: 500,
        top: 1250,
        width: 140,
        text: '제주 원산지',
        fontSize: 16,
        fontFamily: 'Noto Sans KR',
        fontWeight: 'bold',
        fill: '#333333',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
        _customId: 'icon-title-3',
        _customName: '아이콘 제목 3',
      },
      {
        type: 'textbox',
        left: 500,
        top: 1280,
        width: 140,
        text: '국내산 100%',
        fontSize: 13,
        fontFamily: 'Noto Sans KR',
        fill: '#888888',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
        _customId: 'icon-desc-3',
        _customName: '아이콘 설명 3',
      },
      // 아이콘 박스 4
      {
        type: 'rect',
        left: 600,
        top: 1150,
        width: 160,
        height: 180,
        fill: '#FFFFFF',
        rx: 16,
        ry: 16,
        selectable: true,
        _customId: 'icon-box-4',
        _customName: '아이콘 박스 4',
      },
      {
        type: 'textbox',
        left: 680,
        top: 1180,
        width: 100,
        text: '📦',
        fontSize: 48,
        textAlign: 'center',
        originX: 'center',
        selectable: true,
        _customId: 'icon-4',
        _customName: '아이콘 4',
      },
      {
        type: 'textbox',
        left: 680,
        top: 1250,
        width: 140,
        text: '꼼꼼 포장',
        fontSize: 16,
        fontFamily: 'Noto Sans KR',
        fontWeight: 'bold',
        fill: '#333333',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
        _customId: 'icon-title-4',
        _customName: '아이콘 제목 4',
      },
      {
        type: 'textbox',
        left: 680,
        top: 1280,
        width: 140,
        text: '안전하게 배송',
        fontSize: 13,
        fontFamily: 'Noto Sans KR',
        fill: '#888888',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
        _customId: 'icon-desc-4',
        _customName: '아이콘 설명 4',
      },

      // 섹션 4: 프리미엄 포인트
      {
        type: 'rect',
        left: 0,
        top: 1410,
        width: 860,
        height: 400,
        fill: '#FFFFFF',
        selectable: true,
        _customId: 'premium-bg',
        _customName: '프리미엄 섹션 배경',
      },
      {
        type: 'textbox',
        left: 430,
        top: 1450,
        width: 200,
        text: '제주 제철의 선물',
        fontSize: 14,
        fontFamily: 'Noto Sans KR',
        fill: '#FF9800',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
        _customId: 'premium-badge',
        _customName: '프리미엄 라벨',
      },
      {
        type: 'textbox',
        left: 430,
        top: 1490,
        width: 700,
        text: '최상급 감귤만을 엄선했습니다',
        fontSize: 32,
        fontFamily: 'Noto Sans KR',
        fontWeight: 'bold',
        fill: '#333333',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
        _customId: 'premium-title',
        _customName: '프리미엄 제목',
      },
      {
        type: 'textbox',
        left: 430,
        top: 1560,
        width: 600,
        text: '제주도의 청정 자연에서 자란 감귤은 일교차가 큰 환경에서\n당도가 높아지고, 해풍을 맞으며 미네랄이 풍부해집니다.\n\n저희는 그중에서도 가장 품질 좋은 감귤만을 선별하여\n고객님께 보내드립니다.',
        fontSize: 16,
        fontFamily: 'Noto Sans KR',
        fill: '#666666',
        textAlign: 'center',
        originX: 'center',
        lineHeight: 1.8,
        selectable: true,
        _customId: 'premium-desc',
        _customName: '프리미엄 설명',
      },

      // 섹션 5: 사이즈/용량 안내
      {
        type: 'rect',
        left: 0,
        top: 1830,
        width: 860,
        height: 350,
        fill: '#FFF8E1',
        selectable: true,
        _customId: 'size-bg',
        _customName: '사이즈 섹션 배경',
      },
      {
        type: 'textbox',
        left: 430,
        top: 1870,
        width: 300,
        text: '사이즈 안내',
        fontSize: 24,
        fontFamily: 'Noto Sans KR',
        fontWeight: 'bold',
        fill: '#333333',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
        _customId: 'size-title',
        _customName: '사이즈 제목',
      },
      // 사이즈 박스들
      {
        type: 'rect',
        left: 100,
        top: 1940,
        width: 180,
        height: 120,
        fill: '#FFFFFF',
        rx: 12,
        ry: 12,
        selectable: true,
        _customId: 'size-box-1',
        _customName: '용량 박스 1',
      },
      {
        type: 'textbox',
        left: 190,
        top: 1960,
        width: 160,
        text: '총 중량',
        fontSize: 13,
        fontFamily: 'Noto Sans KR',
        fill: '#888888',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
        _customId: 'size-label-1',
        _customName: '용량 라벨 1',
      },
      {
        type: 'textbox',
        left: 190,
        top: 1995,
        width: 160,
        text: '5kg',
        fontSize: 28,
        fontFamily: 'Noto Sans KR',
        fontWeight: 'bold',
        fill: '#FF9800',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
        _customId: 'size-value-1',
        _customName: '용량 값 1',
      },
      {
        type: 'rect',
        left: 300,
        top: 1940,
        width: 180,
        height: 120,
        fill: '#FFFFFF',
        rx: 12,
        ry: 12,
        selectable: true,
        _customId: 'size-box-2',
        _customName: '용량 박스 2',
      },
      {
        type: 'textbox',
        left: 390,
        top: 1960,
        width: 160,
        text: '실중량',
        fontSize: 13,
        fontFamily: 'Noto Sans KR',
        fill: '#888888',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
        _customId: 'size-label-2',
        _customName: '용량 라벨 2',
      },
      {
        type: 'textbox',
        left: 390,
        top: 1995,
        width: 160,
        text: '4.5kg',
        fontSize: 28,
        fontFamily: 'Noto Sans KR',
        fontWeight: 'bold',
        fill: '#FF9800',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
        _customId: 'size-value-2',
        _customName: '용량 값 2',
      },
      {
        type: 'rect',
        left: 500,
        top: 1940,
        width: 180,
        height: 120,
        fill: '#FFFFFF',
        rx: 12,
        ry: 12,
        selectable: true,
        _customId: 'size-box-3',
        _customName: '용량 박스 3',
      },
      {
        type: 'textbox',
        left: 590,
        top: 1960,
        width: 160,
        text: '크기',
        fontSize: 13,
        fontFamily: 'Noto Sans KR',
        fill: '#888888',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
        _customId: 'size-label-3',
        _customName: '용량 라벨 3',
      },
      {
        type: 'textbox',
        left: 590,
        top: 1995,
        width: 160,
        text: '2S~S',
        fontSize: 28,
        fontFamily: 'Noto Sans KR',
        fontWeight: 'bold',
        fill: '#FF9800',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
        _customId: 'size-value-3',
        _customName: '용량 값 3',
      },
      {
        type: 'textbox',
        left: 430,
        top: 2090,
        width: 500,
        text: '※ 자연산 농산물 특성상 크기와 중량에 약간의 차이가 있을 수 있습니다',
        fontSize: 13,
        fontFamily: 'Noto Sans KR',
        fill: '#999999',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
        _customId: 'size-notice',
        _customName: '사이즈 안내문구',
      },

      // 섹션 6: 배송/안내 정보
      {
        type: 'rect',
        left: 0,
        top: 2200,
        width: 860,
        height: 500,
        fill: '#FFFFFF',
        selectable: true,
        _customId: 'delivery-bg',
        _customName: '배송정보 배경',
      },
      {
        type: 'textbox',
        left: 430,
        top: 2240,
        width: 300,
        text: '배송 안내',
        fontSize: 24,
        fontFamily: 'Noto Sans KR',
        fontWeight: 'bold',
        fill: '#333333',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
        _customId: 'delivery-title',
        _customName: '배송정보 제목',
      },
      {
        type: 'rect',
        left: 80,
        top: 2300,
        width: 700,
        height: 280,
        fill: '#F8F9FA',
        rx: 16,
        ry: 16,
        selectable: true,
        _customId: 'delivery-box',
        _customName: '배송정보 박스',
      },
      {
        type: 'textbox',
        left: 120,
        top: 2330,
        width: 100,
        text: '배송방법',
        fontSize: 15,
        fontFamily: 'Noto Sans KR',
        fontWeight: 'bold',
        fill: '#666666',
        selectable: true,
        _customId: 'delivery-method-label',
        _customName: '배송방법 라벨',
      },
      {
        type: 'textbox',
        left: 230,
        top: 2330,
        width: 500,
        text: '택배배송 (CJ대한통운)',
        fontSize: 15,
        fontFamily: 'Noto Sans KR',
        fill: '#333333',
        selectable: true,
        _customId: 'delivery-method-value',
        _customName: '배송방법 값',
      },
      {
        type: 'textbox',
        left: 120,
        top: 2370,
        width: 100,
        text: '배송기간',
        fontSize: 15,
        fontFamily: 'Noto Sans KR',
        fontWeight: 'bold',
        fill: '#666666',
        selectable: true,
        _customId: 'delivery-duration-label',
        _customName: '배송기간 라벨',
      },
      {
        type: 'textbox',
        left: 230,
        top: 2370,
        width: 500,
        text: '결제 완료 후 2~3일 이내 출고',
        fontSize: 15,
        fontFamily: 'Noto Sans KR',
        fill: '#333333',
        selectable: true,
        _customId: 'delivery-duration-value',
        _customName: '배송기간 값',
      },
      {
        type: 'textbox',
        left: 120,
        top: 2410,
        width: 100,
        text: '보관방법',
        fontSize: 15,
        fontFamily: 'Noto Sans KR',
        fontWeight: 'bold',
        fill: '#666666',
        selectable: true,
        _customId: 'delivery-storage-label',
        _customName: '보관방법 라벨',
      },
      {
        type: 'textbox',
        left: 230,
        top: 2410,
        width: 500,
        text: '직사광선을 피해 서늘한 곳에 보관',
        fontSize: 15,
        fontFamily: 'Noto Sans KR',
        fill: '#333333',
        selectable: true,
        _customId: 'delivery-storage-value',
        _customName: '보관방법 값',
      },
      {
        type: 'textbox',
        left: 120,
        top: 2470,
        width: 150,
        text: '📌 주의사항',
        fontSize: 14,
        fontFamily: 'Noto Sans KR',
        fontWeight: 'bold',
        fill: '#666666',
        selectable: true,
        _customId: 'caution-label',
        _customName: '주의사항 라벨',
      },
      {
        type: 'textbox',
        left: 120,
        top: 2500,
        width: 640,
        text: '• 자연산 농산물로 크기, 당도에 차이가 있을 수 있습니다\n• 수령 후 바로 개봉하여 상태 확인 부탁드립니다\n• 신선식품 특성상 단순 변심 교환/환불이 어렵습니다',
        fontSize: 13,
        fontFamily: 'Noto Sans KR',
        fill: '#666666',
        lineHeight: 1.8,
        selectable: true,
        _customId: 'caution-text',
        _customName: '주의사항 내용',
      },

      // 섹션 7: 푸터
      {
        type: 'rect',
        left: 0,
        top: 2720,
        width: 860,
        height: 150,
        fill: '#FFF3E0',
        selectable: true,
        _customId: 'footer-bg',
        _customName: '푸터 배경',
      },
      {
        type: 'textbox',
        left: 430,
        top: 2770,
        width: 500,
        text: '🍊 감귤 맛있게 드세요~!',
        fontSize: 16,
        fontFamily: 'Noto Sans KR',
        fill: '#888888',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
        _customId: 'footer-text',
        _customName: '푸터 텍스트',
      },
      {
        type: 'textbox',
        left: 430,
        top: 2810,
        width: 500,
        text: '더 궁금하신 사항은 문의 부탁드립니다',
        fontSize: 13,
        fontFamily: 'Noto Sans KR',
        fill: '#AAAAAA',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
        _customId: 'footer-contact',
        _customName: '푸터 연락처',
      },
    ],
  },
};

// 사과 상세페이지 템플릿
const appleDetailTemplate: CanvasTemplate = {
  id: 'fruit-apple',
  name: '과일 상세페이지 (사과 스타일)',
  category: 'fruit',
  description: '청송/경북 사과 스타일의 프리미엄 상세페이지',
  thumbnail: '#E53935',
  canvasHeight: 3500,
  fabricJson: {
    version: '6.0.0',
    objects: [
      // 헤더 배너
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: 860,
        height: 400,
        fill: '#FFEBEE',
        selectable: true,
        _customId: 'header-bg',
        _customName: '헤더 배경',
      },
      {
        type: 'textbox',
        left: 430,
        top: 80,
        width: 700,
        text: '🍎 경북 청송',
        fontSize: 24,
        fontFamily: 'Noto Sans KR',
        fill: '#C62828',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
        _customId: 'header-badge',
        _customName: '상단 라벨',
      },
      {
        type: 'textbox',
        left: 430,
        top: 140,
        width: 700,
        text: '아삭아삭 달콤한\n청송 꿀사과',
        fontSize: 48,
        fontFamily: 'Noto Sans KR',
        fontWeight: 'bold',
        fill: '#B71C1C',
        textAlign: 'center',
        originX: 'center',
        lineHeight: 1.3,
        selectable: true,
        _customId: 'main-title',
        _customName: '메인 타이틀',
      },
      {
        type: 'textbox',
        left: 430,
        top: 280,
        width: 600,
        text: '일교차 큰 산지에서 자란 프리미엄 사과\n당도와 식감 모두 최상급',
        fontSize: 18,
        fontFamily: 'Noto Sans KR',
        fill: '#666666',
        textAlign: 'center',
        originX: 'center',
        lineHeight: 1.5,
        selectable: true,
        _customId: 'sub-title',
        _customName: '서브 타이틀',
      },
      // 상품 소개 섹션
      {
        type: 'rect',
        left: 0,
        top: 420,
        width: 860,
        height: 500,
        fill: '#FFFFFF',
        selectable: true,
        _customId: 'intro-bg',
        _customName: '상품소개 배경',
      },
      {
        type: 'textbox',
        left: 430,
        top: 460,
        width: 600,
        text: '대체 무슨 사과이길래?',
        fontSize: 18,
        fontFamily: 'Noto Sans KR',
        fill: '#999999',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
        _customId: 'intro-question',
        _customName: '인트로 질문',
      },
      {
        type: 'textbox',
        left: 430,
        top: 500,
        width: 700,
        text: '저희가 판매하는 사과는요~!',
        fontSize: 28,
        fontFamily: 'Noto Sans KR',
        fontWeight: 'bold',
        fill: '#333333',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
        _customId: 'intro-title',
        _customName: '소개 제목',
      },
      {
        type: 'rect',
        left: 80,
        top: 570,
        width: 700,
        height: 60,
        fill: '#FFEBEE',
        rx: 12,
        ry: 12,
        selectable: true,
        _customId: 'feature-1-bg',
        _customName: '특징1 배경',
      },
      {
        type: 'textbox',
        left: 100,
        top: 585,
        width: 660,
        text: '✓ 청송 고랭지에서 재배한 프리미엄 사과',
        fontSize: 18,
        fontFamily: 'Noto Sans KR',
        fontWeight: '500',
        fill: '#333333',
        selectable: true,
        _customId: 'feature-1-text',
        _customName: '특징1 텍스트',
      },
      {
        type: 'rect',
        left: 80,
        top: 650,
        width: 700,
        height: 60,
        fill: '#FFEBEE',
        rx: 12,
        ry: 12,
        selectable: true,
        _customId: 'feature-2-bg',
        _customName: '특징2 배경',
      },
      {
        type: 'textbox',
        left: 100,
        top: 665,
        width: 660,
        text: '✓ 14Brix 이상 고당도 선별',
        fontSize: 18,
        fontFamily: 'Noto Sans KR',
        fontWeight: '500',
        fill: '#333333',
        selectable: true,
        _customId: 'feature-2-text',
        _customName: '특징2 텍스트',
      },
      {
        type: 'rect',
        left: 80,
        top: 730,
        width: 700,
        height: 60,
        fill: '#FFEBEE',
        rx: 12,
        ry: 12,
        selectable: true,
        _customId: 'feature-3-bg',
        _customName: '특징3 배경',
      },
      {
        type: 'textbox',
        left: 100,
        top: 745,
        width: 660,
        text: '✓ 아삭한 식감과 풍부한 과즙',
        fontSize: 18,
        fontFamily: 'Noto Sans KR',
        fontWeight: '500',
        fill: '#333333',
        selectable: true,
        _customId: 'feature-3-text',
        _customName: '특징3 텍스트',
      },
      // 이미지 플레이스홀더
      {
        type: 'rect',
        left: 180,
        top: 830,
        width: 500,
        height: 160,
        fill: '#F5F5F5',
        rx: 16,
        ry: 16,
        stroke: '#E0E0E0',
        strokeWidth: 2,
        strokeDashArray: [8, 4],
        selectable: true,
        _customId: 'product-image-placeholder',
        _customName: '상품 이미지 영역',
      },
      // ... 나머지 섹션들은 감귤 템플릿과 유사하게 색상만 변경
    ],
  },
};

// 수산물 상세페이지 템플릿
const seafoodDetailTemplate: CanvasTemplate = {
  id: 'seafood-fish',
  name: '수산물 상세페이지',
  category: 'seafood',
  description: '신선한 수산물 상세페이지 템플릿',
  thumbnail: '#0277BD',
  canvasHeight: 3500,
  fabricJson: {
    version: '6.0.0',
    objects: [
      // 헤더
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: 860,
        height: 400,
        fill: '#E3F2FD',
        selectable: true,
        _customId: 'header-bg',
        _customName: '헤더 배경',
      },
      {
        type: 'textbox',
        left: 430,
        top: 80,
        width: 700,
        text: '🐟 산지직송 수산물',
        fontSize: 24,
        fontFamily: 'Noto Sans KR',
        fill: '#0277BD',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
        _customId: 'header-badge',
        _customName: '상단 라벨',
      },
      {
        type: 'textbox',
        left: 430,
        top: 140,
        width: 700,
        text: '바다의 신선함을\n그대로 담았습니다',
        fontSize: 48,
        fontFamily: 'Noto Sans KR',
        fontWeight: 'bold',
        fill: '#01579B',
        textAlign: 'center',
        originX: 'center',
        lineHeight: 1.3,
        selectable: true,
        _customId: 'main-title',
        _customName: '메인 타이틀',
      },
      {
        type: 'textbox',
        left: 430,
        top: 280,
        width: 600,
        text: '어획 당일 바로 출고\n최상의 신선도를 보장합니다',
        fontSize: 18,
        fontFamily: 'Noto Sans KR',
        fill: '#666666',
        textAlign: 'center',
        originX: 'center',
        lineHeight: 1.5,
        selectable: true,
        _customId: 'sub-title',
        _customName: '서브 타이틀',
      },
      // 상품 소개 섹션
      {
        type: 'rect',
        left: 0,
        top: 420,
        width: 860,
        height: 500,
        fill: '#FFFFFF',
        selectable: true,
        _customId: 'intro-bg',
        _customName: '상품소개 배경',
      },
      {
        type: 'textbox',
        left: 430,
        top: 500,
        width: 700,
        text: '저희가 판매하는 수산물은요~!',
        fontSize: 28,
        fontFamily: 'Noto Sans KR',
        fontWeight: 'bold',
        fill: '#333333',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
        _customId: 'intro-title',
        _customName: '소개 제목',
      },
      {
        type: 'rect',
        left: 80,
        top: 570,
        width: 700,
        height: 60,
        fill: '#E3F2FD',
        rx: 12,
        ry: 12,
        selectable: true,
        _customId: 'feature-1-bg',
        _customName: '특징1 배경',
      },
      {
        type: 'textbox',
        left: 100,
        top: 585,
        width: 660,
        text: '✓ 당일 어획, 당일 출고 원칙',
        fontSize: 18,
        fontFamily: 'Noto Sans KR',
        fontWeight: '500',
        fill: '#333333',
        selectable: true,
        _customId: 'feature-1-text',
        _customName: '특징1 텍스트',
      },
      {
        type: 'rect',
        left: 80,
        top: 650,
        width: 700,
        height: 60,
        fill: '#E3F2FD',
        rx: 12,
        ry: 12,
        selectable: true,
        _customId: 'feature-2-bg',
        _customName: '특징2 배경',
      },
      {
        type: 'textbox',
        left: 100,
        top: 665,
        width: 660,
        text: '✓ 아이스박스 + 아이스팩 완벽 냉장 배송',
        fontSize: 18,
        fontFamily: 'Noto Sans KR',
        fontWeight: '500',
        fill: '#333333',
        selectable: true,
        _customId: 'feature-2-text',
        _customName: '특징2 텍스트',
      },
      {
        type: 'rect',
        left: 80,
        top: 730,
        width: 700,
        height: 60,
        fill: '#E3F2FD',
        rx: 12,
        ry: 12,
        selectable: true,
        _customId: 'feature-3-bg',
        _customName: '특징3 배경',
      },
      {
        type: 'textbox',
        left: 100,
        top: 745,
        width: 660,
        text: '✓ 손질 완료 상태로 배송 (옵션 선택)',
        fontSize: 18,
        fontFamily: 'Noto Sans KR',
        fontWeight: '500',
        fill: '#333333',
        selectable: true,
        _customId: 'feature-3-text',
        _customName: '특징3 텍스트',
      },
      // 이미지 플레이스홀더
      {
        type: 'rect',
        left: 180,
        top: 830,
        width: 500,
        height: 160,
        fill: '#F5F5F5',
        rx: 16,
        ry: 16,
        stroke: '#E0E0E0',
        strokeWidth: 2,
        strokeDashArray: [8, 4],
        selectable: true,
        _customId: 'product-image-placeholder',
        _customName: '상품 이미지 영역',
      },
    ],
  },
};

// 일반 상품 템플릿
const generalProductTemplate: CanvasTemplate = {
  id: 'general-product',
  name: '일반 상품 상세페이지',
  category: 'general',
  description: '다양한 상품에 사용 가능한 기본 템플릿',
  thumbnail: '#7B1FA2',
  canvasHeight: 2500,
  fabricJson: {
    version: '6.0.0',
    objects: [
      // 헤더
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: 860,
        height: 350,
        fill: '#F3E5F5',
        selectable: true,
        _customId: 'header-bg',
        _customName: '헤더 배경',
      },
      {
        type: 'textbox',
        left: 430,
        top: 100,
        width: 700,
        text: '상품명을 입력하세요',
        fontSize: 42,
        fontFamily: 'Noto Sans KR',
        fontWeight: 'bold',
        fill: '#4A148C',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
        _customId: 'main-title',
        _customName: '메인 타이틀',
      },
      {
        type: 'textbox',
        left: 430,
        top: 180,
        width: 600,
        text: '상품의 핵심 가치를 설명해주세요',
        fontSize: 18,
        fontFamily: 'Noto Sans KR',
        fill: '#666666',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
        _customId: 'sub-title',
        _customName: '서브 타이틀',
      },
      // 특징 섹션
      {
        type: 'rect',
        left: 0,
        top: 370,
        width: 860,
        height: 400,
        fill: '#FFFFFF',
        selectable: true,
        _customId: 'features-bg',
        _customName: '특징 섹션 배경',
      },
      {
        type: 'textbox',
        left: 430,
        top: 410,
        width: 700,
        text: '이 상품의 특별한 점',
        fontSize: 28,
        fontFamily: 'Noto Sans KR',
        fontWeight: 'bold',
        fill: '#333333',
        textAlign: 'center',
        originX: 'center',
        selectable: true,
        _customId: 'features-title',
        _customName: '특징 제목',
      },
      {
        type: 'rect',
        left: 80,
        top: 480,
        width: 700,
        height: 60,
        fill: '#F3E5F5',
        rx: 12,
        ry: 12,
        selectable: true,
        _customId: 'feature-1-bg',
        _customName: '특징1 배경',
      },
      {
        type: 'textbox',
        left: 100,
        top: 495,
        width: 660,
        text: '✓ 첫 번째 특징을 입력하세요',
        fontSize: 18,
        fontFamily: 'Noto Sans KR',
        fontWeight: '500',
        fill: '#333333',
        selectable: true,
        _customId: 'feature-1-text',
        _customName: '특징1 텍스트',
      },
      {
        type: 'rect',
        left: 80,
        top: 560,
        width: 700,
        height: 60,
        fill: '#F3E5F5',
        rx: 12,
        ry: 12,
        selectable: true,
        _customId: 'feature-2-bg',
        _customName: '특징2 배경',
      },
      {
        type: 'textbox',
        left: 100,
        top: 575,
        width: 660,
        text: '✓ 두 번째 특징을 입력하세요',
        fontSize: 18,
        fontFamily: 'Noto Sans KR',
        fontWeight: '500',
        fill: '#333333',
        selectable: true,
        _customId: 'feature-2-text',
        _customName: '특징2 텍스트',
      },
      {
        type: 'rect',
        left: 80,
        top: 640,
        width: 700,
        height: 60,
        fill: '#F3E5F5',
        rx: 12,
        ry: 12,
        selectable: true,
        _customId: 'feature-3-bg',
        _customName: '특징3 배경',
      },
      {
        type: 'textbox',
        left: 100,
        top: 655,
        width: 660,
        text: '✓ 세 번째 특징을 입력하세요',
        fontSize: 18,
        fontFamily: 'Noto Sans KR',
        fontWeight: '500',
        fill: '#333333',
        selectable: true,
        _customId: 'feature-3-text',
        _customName: '특징3 텍스트',
      },
    ],
  },
};

// 템플릿 목록
export const CANVAS_TEMPLATES: CanvasTemplate[] = [
  fruitDetailTemplate,
  appleDetailTemplate,
  seafoodDetailTemplate,
  generalProductTemplate,
];

export function getTemplateById(id: string): CanvasTemplate | undefined {
  return CANVAS_TEMPLATES.find((t) => t.id === id);
}

export function getTemplatesByCategory(category: CanvasTemplate['category']): CanvasTemplate[] {
  return CANVAS_TEMPLATES.filter((t) => t.category === category);
}
